/* Банк вопросов и карточек тренажёра «Preposizioni».
 *
 * ВАЖНО: итальянские примеры составлены Claude и ещё НЕ проверены носителем/репетитором.
 * Перед регулярным использованием показать репетитору (файл docs/Банк_для_репетитора.md).
 *
 * Формат вопроса:  id, cat, ru (перевод — фиксирует смысл), q (предложение с ___),
 *                  o (варианты), a (правильный), why (объяснение).
 * Формат карточки: id, cat, f (русский), b (итальянский), ex (пример).
 * cat: place (место) | time (время) | verb (глагол+предлог) | art (слияния) | other (другое)
 * Знак «—» в вариантах значит «без предлога».
 */
window.QUESTIONS = [
  /* ---------- МЕСТО ---------- */
  {"id":"p01","cat":"place","ru":"Я живу в Риме.","q":"Vivo ___ Roma.","o":["a","in","da","di"],"a":"a","why":"Город → a (a Roma, a Milano)."},
  {"id":"p02","cat":"place","ru":"Я живу в Италии.","q":"Vivo ___ Italia.","o":["a","in","da","di"],"a":"in","why":"Страна, регион, континент → in (in Italia, in Toscana, in Europa)."},
  {"id":"p03","cat":"place","ru":"Завтра я еду в Милан.","q":"Domani vado ___ Milano.","o":["a","in","da","di"],"a":"a","why":"Город → a, и «где», и «куда»."},
  {"id":"p04","cat":"place","ru":"Я еду во Францию.","q":"Vado ___ Francia.","o":["a","in","da","di"],"a":"in","why":"Страна → in."},
  {"id":"p05","cat":"place","ru":"Вечером я иду к Марко.","q":"Stasera vado ___ Marco.","o":["a","in","da","di"],"a":"da","why":"К человеку / у человека → da (da Marco, da Maria)."},
  {"id":"p06","cat":"place","ru":"Я родом из Рима.","q":"Sono ___ Roma.","o":["di","a","in","su"],"a":"di","why":"Происхождение («родом из») → di. Для «приехал из» → da: Vengo da Roma."},
  {"id":"p07","cat":"place","ru":"Я приехал из Неаполя.","q":"Vengo ___ Napoli.","o":["da","di","a","in"],"a":"da","why":"Откуда (движение) → da. Для «родом из» → di: Sono di Napoli."},
  {"id":"p08","cat":"place","ru":"Я иду домой.","q":"Vado ___ casa.","o":["a","da","di","su"],"a":"a","why":"a casa — устойчивый блок («дома / домой»)."},
  {"id":"p09","cat":"place","ru":"Дети в школе.","q":"I bambini sono ___ scuola.","o":["a","da","di","su"],"a":"a","why":"a scuola — устойчивый блок."},
  {"id":"p10","cat":"place","ru":"Я работаю в банке.","q":"Lavoro ___ banca.","o":["in","a","da","di"],"a":"in","why":"in banca — блок. Помещения без чёткого правила: учим парами."},
  {"id":"p11","cat":"place","ru":"Он работает в офисе.","q":"Lui lavora ___ ufficio.","o":["in","a","da","su"],"a":"in","why":"in ufficio — блок."},
  {"id":"p12","cat":"place","ru":"Я иду в аптеку.","q":"Vado ___ farmacia.","o":["in","a","da","di"],"a":"in","why":"in farmacia — блок."},
  {"id":"p13","cat":"place","ru":"Я иду в центр.","q":"Vado ___ centro.","o":["in","a","da","di"],"a":"in","why":"in centro — блок."},
  {"id":"p14","cat":"place","ru":"Мы в отпуске.","q":"Siamo ___ vacanza.","o":["in","a","da","di"],"a":"in","why":"in vacanza — блок."},
  {"id":"p15","cat":"place","ru":"Мы в горах.","q":"Siamo ___ montagna.","o":["in","a","da","su"],"a":"in","why":"in montagna — блок."},
  {"id":"p16","cat":"place","ru":"Я еду на поезде.","q":"Vado ___ treno.","o":["in","da","di","su"],"a":"in","why":"Транспорт → in (in treno, in macchina, in aereo)."},
  {"id":"p17","cat":"place","ru":"Я иду пешком.","q":"Vado ___ piedi.","o":["a","in","da","di"],"a":"a","why":"Пешком — исключение из «транспорта → in»: a piedi."},
  {"id":"p18","cat":"place","ru":"Я еду на машине.","q":"Vado ___ macchina.","o":["in","da","di","su"],"a":"in","why":"Транспорт → in."},
  {"id":"p19","cat":"place","ru":"Сегодня вечером мы у Марии.","q":"Stasera siamo ___ Maria.","o":["da","a","in","di"],"a":"da","why":"«У человека, в гостях у» → da (da Maria, da Marco)."},
  {"id":"p20","cat":"place","ru":"Я иду к врачу.","q":"Vado ___ medico.","o":["dal","nel","sul","del"],"a":"dal","why":"К врачу, в пекарню, к парикмахеру → da + артикль: dal medico (da + il = dal)."},
  {"id":"p21","cat":"place","ru":"Мы в кинотеатре.","q":"Siamo ___ cinema.","o":["al","dal","del","sul"],"a":"al","why":"al cinema — блок (a + il = al)."},
  {"id":"p22","cat":"place","ru":"Мы идём в ресторан.","q":"Andiamo ___ ristorante.","o":["al","del","sul","dal"],"a":"al","why":"al ristorante — блок (a + il = al)."},
  {"id":"p23","cat":"place","ru":"Я еду в Тоскану.","q":"Vado ___ Toscana.","o":["in","a","da","di"],"a":"in","why":"Регион → in."},
  {"id":"p24","cat":"place","ru":"Мы живём в Турине.","q":"Abitiamo ___ Torino.","o":["a","in","da","di"],"a":"a","why":"Город → a."},
  {"id":"p25","cat":"place","ru":"Мы живём в Европе.","q":"Viviamo ___ Europa.","o":["in","a","da","su"],"a":"in","why":"Континент → in."},
  {"id":"p26","cat":"place","ru":"Я приезжаю в Милан.","q":"Arrivo ___ Milano.","o":["a","in","da","di"],"a":"a","why":"Город (куда) → a. Arrivo da Milano — «приезжаю из Милана»."},
  {"id":"p27","cat":"place","ru":"Я возвращаюсь в Италию.","q":"Torno ___ Italia.","o":["in","a","da","di"],"a":"in","why":"Страна → in."},
  {"id":"p28","cat":"place","ru":"Она в библиотеке.","q":"Lei è ___ biblioteca.","o":["in","a","da","su"],"a":"in","why":"in biblioteca — блок."},
  {"id":"p29","cat":"place","ru":"Мы на площади.","q":"Siamo ___ piazza.","o":["in","a","da","su"],"a":"in","why":"in piazza — блок."},
  {"id":"p30","cat":"place","ru":"Я иду в спортзал.","q":"Vado ___ palestra.","o":["in","a","da","di"],"a":"in","why":"in palestra — блок."},

  /* ---------- ВРЕМЯ ---------- */
  {"id":"t01","cat":"time","ru":"Я работаю здесь уже два года.","q":"Lavoro qui ___ due anni.","o":["da","per","in","tra"],"a":"da","why":"Началось и длится до сих пор, глагол в настоящем → da."},
  {"id":"t02","cat":"time","ru":"Я два года жил в Милане (теперь уже нет).","q":"Ho abitato a Milano ___ due anni.","o":["da","per","in","tra"],"a":"per","why":"Закончившийся срок → per."},
  {"id":"t03","cat":"time","ru":"Я приеду через два дня.","q":"Arrivo ___ due giorni.","o":["tra","per","da","di"],"a":"tra","why":"«Через» (срок в будущем) → tra или fra."},
  {"id":"t04","cat":"time","ru":"Я закончил работу за час.","q":"Ho finito il lavoro ___ un'ora.","o":["in","per","da","tra"],"a":"in","why":"«За» сколько времени уложился → in."},
  {"id":"t05","cat":"time","ru":"Я учу итальянский с сентября (и сейчас учу).","q":"Studio italiano ___ settembre.","o":["da","per","in","tra"],"a":"da","why":"«С такого-то момента, до сих пор» → da."},
  {"id":"t06","cat":"time","ru":"Фильм начинается в восемь.","q":"Il film inizia ___ otto.","o":["alle","nelle","dalle","delle"],"a":"alle","why":"Час → a + артикль: alle otto (a + le = alle)."},
  {"id":"t07","cat":"time","ru":"Увидимся на Рождество.","q":"Ci vediamo ___ Natale.","o":["a","in","da","su"],"a":"a","why":"Праздник → a (a Natale, a Pasqua)."},
  {"id":"t08","cat":"time","ru":"Зимой холодно.","q":"Fa freddo ___ inverno.","o":["in","a","da","su"],"a":"in","why":"Сезон → in (in estate, in inverno)."},
  {"id":"t09","cat":"time","ru":"Курс начался в 2026 году.","q":"Il corso è iniziato ___ 2026.","o":["nel","al","dal","del"],"a":"nel","why":"Год → in + артикль: nel 2026 (in + il = nel). Dal 2026 — «с 2026»."},
  {"id":"t10","cat":"time","ru":"Летом я езжу на море.","q":"___ estate vado al mare.","o":["In","A","Da","Su"],"a":"In","why":"Сезон → in."},
  {"id":"t11","cat":"time","ru":"Я проспал десять часов.","q":"Ho dormito ___ dieci ore.","o":["per","da","in","tra"],"a":"per","why":"Срок в прошлом, закончился → per (в разговоре его часто опускают)."},
  {"id":"t12","cat":"time","ru":"Я уезжаю на неделю.","q":"Parto ___ una settimana.","o":["per","da","tra","in"],"a":"per","why":"На какой срок → per. Tra una settimana — «через неделю»."},
  {"id":"t13","cat":"time","ru":"Я не вижу Марко уже два месяца.","q":"Non vedo Marco ___ due mesi.","o":["da","per","in","tra"],"a":"da","why":"Длится до сих пор (глагол в настоящем) → da."},
  {"id":"t14","cat":"time","ru":"Поезд отправляется в полночь.","q":"Il treno parte ___ mezzanotte.","o":["a","in","da","su"],"a":"a","why":"Точка во времени → a (a mezzanotte, a mezzogiorno)."},
  {"id":"t15","cat":"time","ru":"Я вернусь через пять минут.","q":"Torno ___ cinque minuti.","o":["tra","per","da","di"],"a":"tra","why":"«Через» → tra или fra."},
  {"id":"t16","cat":"time","ru":"Я успеваю сделать упражнение за пять минут.","q":"Riesco a fare l'esercizio ___ cinque minuti.","o":["in","per","da","tra"],"a":"in","why":"«За» сколько времени → in."},
  {"id":"t17","cat":"time","ru":"Я живу здесь пять лет (и сейчас живу).","q":"Abito qui ___ cinque anni.","o":["da","per","in","tra"],"a":"da","why":"Началось и длится → da + настоящее время."},
  {"id":"t18","cat":"time","ru":"Магазин открывается в девять.","q":"Il negozio apre ___ nove.","o":["alle","nelle","dalle","sulle"],"a":"alle","why":"Час → a + артикль: alle nove."},

  /* ---------- ГЛАГОЛ + ПРЕДЛОГ ---------- */
  {"id":"v01","cat":"verb","ru":"Я думаю о тебе.","q":"Penso ___ te.","o":["a","da","in","su"],"a":"a","why":"pensare a — думать о (пара, учим целиком)."},
  {"id":"v02","cat":"verb","ru":"Я говорю о работе.","q":"Parlo ___ lavoro.","o":["di","a","da","in"],"a":"di","why":"parlare di — говорить о."},
  {"id":"v03","cat":"verb","ru":"Я верю в Бога.","q":"Credo ___ Dio.","o":["in","di","da","su"],"a":"in","why":"credere in — верить в."},
  {"id":"v04","cat":"verb","ru":"Это зависит от тебя.","q":"Dipende ___ te.","o":["da","di","a","su"],"a":"da","why":"dipendere da — зависеть от."},
  {"id":"v05","cat":"verb","ru":"Я начинаю учиться.","q":"Comincio ___ studiare.","o":["a","di","da","per"],"a":"a","why":"cominciare a + инфинитив."},
  {"id":"v06","cat":"verb","ru":"Я заканчиваю работать в шесть.","q":"Finisco ___ lavorare alle sei.","o":["a","di","da","per"],"a":"di","why":"finire di + инфинитив."},
  {"id":"v07","cat":"verb","ru":"Я перестаю курить.","q":"Smetto ___ fumare.","o":["a","di","da","per"],"a":"di","why":"smettere di + инфинитив."},
  {"id":"v08","cat":"verb","ru":"Я учусь играть на пианино.","q":"Imparo ___ suonare il pianoforte.","o":["a","di","da","per"],"a":"a","why":"imparare a + инфинитив."},
  {"id":"v09","cat":"verb","ru":"Я помогаю тебе готовить.","q":"Ti aiuto ___ cucinare.","o":["a","di","da","in"],"a":"a","why":"aiutare a + инфинитив."},
  {"id":"v10","cat":"verb","ru":"Мне нужна помощь.","q":"Ho bisogno ___ aiuto.","o":["a","di","da","in"],"a":"di","why":"avere bisogno di — нуждаться в."},
  {"id":"v11","cat":"verb","ru":"Я жду поезд.","q":"Aspetto ___ il treno.","o":["—","a","per","di"],"a":"—","why":"aspettare — БЕЗ предлога (в русском «ждать» тоже без: ждать поезд)."},
  {"id":"v12","cat":"verb","ru":"Я слушаю музыку.","q":"Ascolto ___ la musica.","o":["—","a","di","per"],"a":"—","why":"ascoltare — без предлога."},
  {"id":"v13","cat":"verb","ru":"Я ищу ключи.","q":"Cerco ___ le chiavi.","o":["—","di","a","per"],"a":"—","why":"cercare + существительное — без предлога. (cercare di + инфинитив = «пытаться»)."},
  {"id":"v14","cat":"verb","ru":"Я смотрю телевизор.","q":"Guardo ___ la TV.","o":["—","a","di","per"],"a":"—","why":"guardare — без предлога."},
  {"id":"v15","cat":"verb","ru":"Я иду спать.","q":"Vado ___ dormire.","o":["a","di","da","per"],"a":"a","why":"andare a + инфинитив."},
  {"id":"v16","cat":"verb","ru":"Мне хочется мороженого.","q":"Ho voglia ___ gelato.","o":["di","a","per","da"],"a":"di","why":"avere voglia di — хотеться."},
  {"id":"v17","cat":"verb","ru":"Я боюсь темноты.","q":"Ho paura ___ buio.","o":["del","al","nel","sul"],"a":"del","why":"avere paura di + артикль: del buio (di + il = del)."},
  {"id":"v18","cat":"verb","ru":"Я надеюсь скоро тебя увидеть.","q":"Spero ___ vederti presto.","o":["a","di","da","per"],"a":"di","why":"sperare di + инфинитив."},
  {"id":"v19","cat":"verb","ru":"Я пытаюсь понять.","q":"Cerco ___ capire.","o":["—","a","di","da"],"a":"di","why":"cercare di + инфинитив — «пытаться»."},
  {"id":"v20","cat":"verb","ru":"Я готова ехать.","q":"Sono pronta ___ partire.","o":["a","di","da","in"],"a":"a","why":"pronto a + инфинитив."},
  {"id":"v21","cat":"verb","ru":"Я отказываюсь от этой идеи.","q":"Rinuncio ___ questa idea.","o":["a","di","da","su"],"a":"a","why":"rinunciare a — отказываться от."},
  {"id":"v22","cat":"verb","ru":"Я занимаюсь логистикой.","q":"Mi occupo ___ logistica.","o":["di","a","da","in"],"a":"di","why":"occuparsi di — заниматься чем-то."},
  {"id":"v23","cat":"verb","ru":"Я захожу в дом.","q":"Entro ___ casa.","o":["in","a","da","di"],"a":"in","why":"entrare in — входить в."},
  {"id":"v24","cat":"verb","ru":"Я звоню Марко.","q":"Telefono ___ Marco.","o":["a","da","di","con"],"a":"a","why":"telefonare a qualcuno — звонить кому-то."},
  {"id":"v25","cat":"verb","ru":"Я играю в футбол.","q":"Gioco ___ calcio.","o":["a","di","in","con"],"a":"a","why":"giocare a — играть в."},
  {"id":"v26","cat":"verb","ru":"Я рассчитываю на тебя.","q":"Conto ___ te.","o":["su","a","di","da"],"a":"su","why":"contare su — рассчитывать на."},
  {"id":"v27","cat":"verb","ru":"Мне нравится петь.","q":"Mi piace ___ cantare.","o":["—","di","a","per"],"a":"—","why":"piacere + инфинитив — без предлога."},
  {"id":"v28","cat":"verb","ru":"Я решил уехать.","q":"Ho deciso ___ partire.","o":["a","di","da","per"],"a":"di","why":"decidere di + инфинитив."},
  {"id":"v29","cat":"verb","ru":"Я забыл позвонить.","q":"Ho dimenticato ___ chiamare.","o":["a","di","da","per"],"a":"di","why":"dimenticare di + инфинитив."},

  /* ---------- СЛИЯНИЯ ПРЕДЛОГ + АРТИКЛЬ ---------- */
  {"id":"a01","cat":"art","ru":"Книга мальчика.","q":"Il libro ___ ragazzo.","o":["del","dello","della","dei"],"a":"del","why":"di + il = del (ragazzo берёт артикль il)."},
  {"id":"a02","cat":"art","ru":"Я иду на вокзал.","q":"Vado ___ stazione.","o":["alla","della","sulla","dalla"],"a":"alla","why":"a + la = alla."},
  {"id":"a03","cat":"art","ru":"Кот на столе.","q":"Il gatto è ___ tavolo.","o":["sul","nel","dal","del"],"a":"sul","why":"su + il = sul."},
  {"id":"a04","cat":"art","ru":"Я выхожу из офиса в шесть.","q":"Esco ___ ufficio alle sei.","o":["dall'","nell'","sull'","dell'"],"a":"dall'","why":"da + l' = dall' (перед гласной)."},
  {"id":"a05","cat":"art","ru":"Я дарю цветы девушкам.","q":"Regalo i fiori ___ ragazze.","o":["alle","dalle","nelle","delle"],"a":"alle","why":"a + le = alle."},
  {"id":"a06","cat":"art","ru":"Дом дядей большой.","q":"La casa ___ zii è grande.","o":["degli","agli","negli","sugli"],"a":"degli","why":"di + gli = degli."},
  {"id":"a07","cat":"art","ru":"Я иду в университет.","q":"Vado ___ università.","o":["all'","dell'","sull'","dall'"],"a":"all'","why":"a + l' = all' (all'università — блок)."},
  {"id":"a08","cat":"art","ru":"Сумка девушки.","q":"La borsa ___ ragazza.","o":["della","alla","dalla","sulla"],"a":"della","why":"di + la = della."},
  {"id":"a09","cat":"art","ru":"Тетрадь в рюкзаке.","q":"Il quaderno è ___ zaino.","o":["nello","sullo","dallo","dello"],"a":"nello","why":"in + lo = nello (lo zaino)."},
  {"id":"a10","cat":"art","ru":"Ключи в сумке.","q":"Le chiavi sono ___ borsa.","o":["nella","sulla","dalla","della"],"a":"nella","why":"in + la = nella."},
  {"id":"a11","cat":"art","ru":"Я получаю письмо от подруги.","q":"Ricevo una lettera ___ amica.","o":["dall'","all'","nell'","sull'"],"a":"dall'","why":"da + l' = dall' («от»)."},
  {"id":"a12","cat":"art","ru":"Телефон мальчиков.","q":"Il telefono ___ ragazzi.","o":["dei","ai","dai","nei"],"a":"dei","why":"di + i = dei."},
  {"id":"a13","cat":"art","ru":"Я иду к врачу (женщине).","q":"Vado ___ dottoressa.","o":["dalla","alla","nella","sulla"],"a":"dalla","why":"К человеку → da: da + la = dalla."},
  {"id":"a14","cat":"art","ru":"Подарки детям.","q":"I regali ___ bambini.","o":["ai","dai","nei","dei"],"a":"ai","why":"a + i = ai (кому?)."},
  {"id":"a15","cat":"art","ru":"Компьютер на столе.","q":"Il computer è ___ scrivania.","o":["sulla","nella","dalla","della"],"a":"sulla","why":"su + la = sulla."},
  {"id":"a16","cat":"art","ru":"Он идёт к друзьям (в гости).","q":"Va ___ amici.","o":["dagli","agli","negli","degli"],"a":"dagli","why":"К людям → da: da + gli = dagli."},

  /* ---------- ДРУГОЕ (смысл предлога) ---------- */
  {"id":"o01","cat":"other","ru":"Этот подарок для тебя.","q":"Questo regalo è ___ te.","o":["per","di","con","su"],"a":"per","why":"«Для» → per."},
  {"id":"o02","cat":"other","ru":"Сегодня вечером я иду гулять с Марко.","q":"Stasera esco ___ Marco.","o":["con","per","di","su"],"a":"con","why":"«С» → con."},
  {"id":"o03","cat":"other","ru":"Книга написана Данте.","q":"Il libro è scritto ___ Dante.","o":["da","di","per","con"],"a":"da","why":"Кем сделано (пассив) → da."},
  {"id":"o04","cat":"other","ru":"Один кофе, пожалуйста.","q":"Un caffè, ___ favore.","o":["per","di","da","con"],"a":"per","why":"per favore — устойчивое выражение."},
  {"id":"o05","cat":"other","ru":"Это секрет между нами.","q":"Questo è un segreto ___ noi.","o":["tra","per","su","con"],"a":"tra","why":"«Между» → tra или fra."},
  {"id":"o06","cat":"other","ru":"Я пью стакан вина.","q":"Bevo un bicchiere ___ vino.","o":["di","da","per","con"],"a":"di","why":"Содержимое → di: un bicchiere di vino. (da vino = «бокал для вина», см. следующий вопрос)."},
  {"id":"o07","cat":"other","ru":"Бокал для вина (сама посуда).","q":"Un bicchiere ___ vino.","o":["da","di","per","con"],"a":"da","why":"Назначение предмета → da: un bicchiere da vino, una macchina da corsa."},
  {"id":"o08","cat":"other","ru":"Я прочитал книгу о Риме.","q":"Ho letto un libro ___ Roma.","o":["su","per","da","con"],"a":"su","why":"«О» (тема книги, фильма) → su."},
  {"id":"o09","cat":"other","ru":"Я уезжаю в Рим.","q":"Parto ___ Roma.","o":["per","a","in","da"],"a":"per","why":"partire per + место — направление отъезда. Parto da Roma — «уезжаю из Рима»."}
];

window.CARDS = [
  /* ---------- МЕСТО ---------- */
  {"id":"k01","cat":"place","f":"дома / домой","b":"a casa","ex":"Sono a casa. Vado a casa."},
  {"id":"k02","cat":"place","f":"в школе","b":"a scuola","ex":"I bambini sono a scuola."},
  {"id":"k03","cat":"place","f":"в кино","b":"al cinema","ex":"Stasera andiamo al cinema."},
  {"id":"k04","cat":"place","f":"в баре","b":"al bar","ex":"Prendo un caffè al bar."},
  {"id":"k05","cat":"place","f":"в ресторане","b":"al ristorante","ex":"Mangiamo al ristorante."},
  {"id":"k06","cat":"place","f":"в университете","b":"all'università","ex":"Studio all'università."},
  {"id":"k07","cat":"place","f":"на море","b":"al mare","ex":"D'estate vado al mare."},
  {"id":"k08","cat":"place","f":"в театре","b":"a teatro","ex":"Stasera andiamo a teatro."},
  {"id":"k09","cat":"place","f":"в банке","b":"in banca","ex":"Lavoro in banca."},
  {"id":"k10","cat":"place","f":"в офисе","b":"in ufficio","ex":"Sono in ufficio."},
  {"id":"k11","cat":"place","f":"в аптеке","b":"in farmacia","ex":"Vado in farmacia."},
  {"id":"k12","cat":"place","f":"в церкви","b":"in chiesa","ex":"Siamo in chiesa."},
  {"id":"k13","cat":"place","f":"в центре","b":"in centro","ex":"Abito in centro."},
  {"id":"k14","cat":"place","f":"в городе","b":"in città","ex":"Vivo in città."},
  {"id":"k15","cat":"place","f":"в горах","b":"in montagna","ex":"Andiamo in montagna."},
  {"id":"k16","cat":"place","f":"в отпуске","b":"in vacanza","ex":"Siamo in vacanza."},
  {"id":"k17","cat":"place","f":"за городом, в деревне","b":"in campagna","ex":"Abitiamo in campagna."},
  {"id":"k18","cat":"place","f":"в библиотеке","b":"in biblioteca","ex":"Studio in biblioteca."},
  {"id":"k19","cat":"place","f":"в спортзале","b":"in palestra","ex":"Vado in palestra."},
  {"id":"k20","cat":"place","f":"на поезде","b":"in treno","ex":"Viaggio in treno."},
  {"id":"k21","cat":"place","f":"на машине","b":"in macchina","ex":"Vado in macchina."},
  {"id":"k22","cat":"place","f":"на самолёте","b":"in aereo","ex":"Viaggio in aereo."},
  {"id":"k23","cat":"place","f":"на велосипеде","b":"in bicicletta","ex":"Vado in bicicletta."},
  {"id":"k24","cat":"place","f":"пешком","b":"a piedi","ex":"Vado a piedi."},
  {"id":"k25","cat":"place","f":"к врачу","b":"dal medico","ex":"Vado dal medico."},
  {"id":"k26","cat":"place","f":"в пекарню (к булочнику)","b":"dal panettiere","ex":"Vado dal panettiere."},
  {"id":"k27","cat":"place","f":"ко мне / у меня","b":"da me","ex":"Vieni da me stasera."},
  {"id":"k28","cat":"place","f":"к тебе / у тебя","b":"da te","ex":"Vengo da te domani."},
  {"id":"k29","cat":"place","f":"к Марко / у Марко","b":"da Marco","ex":"Stasera vado da Marco."},
  {"id":"k30","cat":"place","f":"в Италии","b":"in Italia","ex":"Vivo in Italia."},
  {"id":"k31","cat":"place","f":"в Риме","b":"a Roma","ex":"Vivo a Roma."},

  /* ---------- ВРЕМЯ ---------- */
  {"id":"k40","cat":"time","f":"с сентября (и до сих пор)","b":"da settembre","ex":"Studio italiano da settembre."},
  {"id":"k41","cat":"time","f":"уже два года","b":"da due anni","ex":"Studio italiano da due anni."},
  {"id":"k42","cat":"time","f":"на неделю (срок)","b":"per una settimana","ex":"Vado a Roma per una settimana."},
  {"id":"k43","cat":"time","f":"два часа (закончено)","b":"per due ore","ex":"Ho studiato per due ore."},
  {"id":"k44","cat":"time","f":"за час (уложился)","b":"in un'ora","ex":"Ho finito in un'ora."},
  {"id":"k45","cat":"time","f":"через два дня","b":"tra due giorni (= fra due giorni)","ex":"Arrivo tra due giorni."},
  {"id":"k46","cat":"time","f":"в восемь (часов)","b":"alle otto","ex":"Ci vediamo alle otto."},
  {"id":"k47","cat":"time","f":"в час дня","b":"all'una","ex":"Pranzo all'una."},
  {"id":"k48","cat":"time","f":"в полночь","b":"a mezzanotte","ex":"Il treno parte a mezzanotte."},
  {"id":"k49","cat":"time","f":"в полдень","b":"a mezzogiorno","ex":"Pranzo a mezzogiorno."},
  {"id":"k50","cat":"time","f":"на Рождество","b":"a Natale","ex":"Ci vediamo a Natale."},
  {"id":"k51","cat":"time","f":"на Пасху","b":"a Pasqua","ex":"A Pasqua andiamo in montagna."},
  {"id":"k52","cat":"time","f":"летом","b":"in estate","ex":"In estate vado al mare."},
  {"id":"k53","cat":"time","f":"зимой","b":"in inverno","ex":"Fa freddo in inverno."},
  {"id":"k54","cat":"time","f":"весной","b":"in primavera","ex":"In primavera fa bel tempo."},
  {"id":"k55","cat":"time","f":"осенью","b":"in autunno","ex":"In autunno piove spesso."},
  {"id":"k56","cat":"time","f":"в 2026 году","b":"nel 2026","ex":"Il corso è iniziato nel 2026."},
  {"id":"k57","cat":"time","f":"в понедельник (в этот)","b":"lunedì (без предлога)","ex":"Lunedì vado in palestra."},
  {"id":"k58","cat":"time","f":"по понедельникам","b":"il lunedì","ex":"Il lunedì vado in palestra."},

  /* ---------- ГЛАГОЛ + ПРЕДЛОГ ---------- */
  {"id":"k70","cat":"verb","f":"думать о","b":"pensare a","ex":"Penso a te."},
  {"id":"k71","cat":"verb","f":"говорить о","b":"parlare di","ex":"Parlo di lavoro."},
  {"id":"k72","cat":"verb","f":"верить в","b":"credere in","ex":"Credo in Dio."},
  {"id":"k73","cat":"verb","f":"зависеть от","b":"dipendere da","ex":"Dipende da te."},
  {"id":"k74","cat":"verb","f":"начинать (делать)","b":"cominciare a + инфинитив","ex":"Comincio a studiare."},
  {"id":"k75","cat":"verb","f":"заканчивать (делать)","b":"finire di + инфинитив","ex":"Finisco di lavorare alle sei."},
  {"id":"k76","cat":"verb","f":"перестать (делать)","b":"smettere di + инфинитив","ex":"Smetto di fumare."},
  {"id":"k77","cat":"verb","f":"учиться (делать)","b":"imparare a + инфинитив","ex":"Imparo a suonare il pianoforte."},
  {"id":"k78","cat":"verb","f":"помогать (делать)","b":"aiutare a + инфинитив","ex":"Ti aiuto a cucinare."},
  {"id":"k79","cat":"verb","f":"нуждаться в","b":"avere bisogno di","ex":"Ho bisogno di aiuto."},
  {"id":"k80","cat":"verb","f":"хотеться (чего-то)","b":"avere voglia di","ex":"Ho voglia di gelato."},
  {"id":"k81","cat":"verb","f":"бояться","b":"avere paura di","ex":"Ho paura del buio."},
  {"id":"k82","cat":"verb","f":"надеяться","b":"sperare di + инфинитив","ex":"Spero di vederti presto."},
  {"id":"k83","cat":"verb","f":"пытаться","b":"cercare di + инфинитив","ex":"Cerco di capire."},
  {"id":"k84","cat":"verb","f":"решить (сделать)","b":"decidere di + инфинитив","ex":"Ho deciso di partire."},
  {"id":"k85","cat":"verb","f":"забыть (сделать)","b":"dimenticare di + инфинитив","ex":"Ho dimenticato di chiamare."},
  {"id":"k86","cat":"verb","f":"звонить (кому-то)","b":"telefonare a","ex":"Telefono a Marco."},
  {"id":"k87","cat":"verb","f":"играть (в игру, спорт)","b":"giocare a","ex":"Gioco a calcio."},
  {"id":"k88","cat":"verb","f":"заниматься (чем-то)","b":"occuparsi di","ex":"Mi occupo di logistica."},
  {"id":"k89","cat":"verb","f":"отказываться от","b":"rinunciare a","ex":"Rinuncio a questa idea."},
  {"id":"k90","cat":"verb","f":"рассчитывать на","b":"contare su","ex":"Conto su di te."},
  {"id":"k91","cat":"verb","f":"входить в","b":"entrare in","ex":"Entro in casa."},
  {"id":"k92","cat":"verb","f":"ждать","b":"aspettare (без предлога)","ex":"Aspetto il treno."},
  {"id":"k93","cat":"verb","f":"слушать","b":"ascoltare (без предлога)","ex":"Ascolto la musica."},
  {"id":"k94","cat":"verb","f":"искать","b":"cercare (без предлога)","ex":"Cerco le chiavi."},
  {"id":"k95","cat":"verb","f":"смотреть","b":"guardare (без предлога)","ex":"Guardo la TV."},
  {"id":"k96","cat":"verb","f":"быть готовой (сделать)","b":"essere pronto a + инфинитив","ex":"Sono pronta a partire."},
  {"id":"k97","cat":"verb","f":"идти (делать что-то)","b":"andare a + инфинитив","ex":"Vado a dormire."},

  /* ---------- ДРУГОЕ ---------- */
  {"id":"k110","cat":"other","f":"пожалуйста (в просьбе)","b":"per favore","ex":"Un caffè, per favore."},
  {"id":"k111","cat":"other","f":"для тебя","b":"per te","ex":"Questo regalo è per te."},
  {"id":"k112","cat":"other","f":"с Марко","b":"con Marco","ex":"Esco con Marco."},
  {"id":"k113","cat":"other","f":"между нами","b":"tra noi (= fra noi)","ex":"È un segreto tra noi."},
  {"id":"k114","cat":"other","f":"стакан вина (содержимое)","b":"un bicchiere di vino","ex":"Bevo un bicchiere di vino."},
  {"id":"k115","cat":"other","f":"бокал для вина (назначение)","b":"un bicchiere da vino","ex":"Ho comprato un bicchiere da vino."},
  {"id":"k116","cat":"other","f":"книга о Риме (тема)","b":"un libro su Roma","ex":"Ho letto un libro su Roma."},
  {"id":"k117","cat":"other","f":"написано кем-то (пассив)","b":"scritto da Dante","ex":"Il libro è scritto da Dante."}
];
